services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - model
  model:
    build: ./model
    ports:
      - "8501:8501"
    environment:
      - MODEL_NAME=food_clf
      - MODEL_BASE_PATH=/models
